# Generated by Django 4.1.3 on 2022-11-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamily', '0002_familiar_delete_familiares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha',
            new_name='nacimiento',
        ),
    ]
