# Generated by Django 4.1.3 on 2022-11-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamily', '0003_rename_fecha_familiar_nacimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiar',
            new_name='familiar1',
        ),
    ]
